#!/bin/bash
clear
echo -e "\E[44;1;37m INSTALADOR BOT VENTAS  \E[0m"
echo -e "\nINSTALANDO ESPERE...."
apt update -y > /dev/null 2>&1 && apt install unzip at jq curl -y > /dev/null 2>&1
mkdir $HOME/BOT
cd $HOME/BOT && wget https://github.com/nefi503sv/botventadragon/raw/main/botventas-main.zip
unzip botventas-main.zip > /dev/null 2>&1 && rm botventas-main.zip > /dev/null 2>&1
chmod +x $(ls)
mv botventas /bin/botventas
clear && echo -e "INSTALACION LISTA !\nPARA ACTIVAR O DESACTIVAR ESCRIBA: botteste"
cd $HOME && rm inst-botventas > /dev/null 2>&1
